# ArewaDS Assignment: 100 numpy exercises

#### Q1. Import the numpy package under the name np

In [1]:
import numpy as np

### Q2. Print the numpy version and the configuration.

In [2]:
print("NumPy v"+ np.__version__)
np.show_config()

NumPy v1.26.0
{
  "Compilers": {
    "c": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "11.2.0",
      "commands": "/croot/numpy_and_numpy_base_1695830428084/_build_env/bin/x86_64-conda-linux-gnu-cc"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.0",
      "commands": "cython"
    },
    "c++": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "11.2.0",
      "commands": "/croot/numpy_and_numpy_base_1695830428084/_build_env/bin/x86_64-conda-linux-gnu-c++"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "linux"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "linux"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "mkl-sdl",
      "found": true,
      "version": "2023.1",
      "detection method": "pkgconfig",
      "include direc

/home/ultimate/miniconda3/envs/datascience/lib/python3.9/site-packages/numpy/__config__.py:149: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


### Q3. Create a null vector of size 10

In [3]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### Q4. How to find the memory size of any array

In [2]:
array = np.zeros((3, 10))
print(array.size * array.itemsize, 'bytes')

240 bytes


### Q5. How to get the documentation of the numpy add function from the command line?


> python -c "import numpy; numpy.info(numpy.add)"

In [5]:
!python -c "import numpy; numpy.info(numpy.add)"

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

### Q6. Create a null vector of size 10 but the fifth value which is 1

In [6]:
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### Q7. Create a vector with values ranging from 10 to 49

In [4]:
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### Q8. Reverse a vector (first element becomes last)

In [5]:
reversed_vector = np.flip(vector)
print(reversed_vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


### Q9. Create a 3x3 matrix with values ranging from 0 to 8

In [9]:
matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Q10. Find indices of non-zero elements from [4, 5, 0, 7, 0, 0]

In [6]:
non_zero_indices = np.nonzero([1,2,0,0,4,0])
print(non_zero_indices)

(array([0, 1, 4], dtype=int64),)


### Q11. Create a 3x3 identity matrix

In [7]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Q12. Create a 3x3x3 array with random values

In [9]:
random_array = np.random.random((3, 3, 3))
print(random_array)

[[[0.88136389 0.59963379 0.9274683 ]
  [0.98390721 0.41421631 0.93975203]
  [0.14948851 0.50013977 0.11897379]]

 [[0.72376736 0.3825147  0.87696647]
  [0.91485773 0.8456692  0.87195306]
  [0.30460011 0.08327617 0.69585267]]

 [[0.02759935 0.4417529  0.97577309]
  [0.29461802 0.24871832 0.16958587]
  [0.19927632 0.7931888  0.84310331]]]


### Q13. Create a 10x10 array with random values and find the minimum and maximum values

In [10]:
random_v = np.random.random((10, 10))
min_value = random_v.min()
max_value = random_v.max()
print(f"10x10 array random values: \n{random_v}")
print(f"\nmin: {min_value}\nmax: {max_value}")

10x10 array random values: 
[[0.18215269 0.76339154 0.62020201 0.08211677 0.87695341 0.56770432
  0.61822182 0.64121666 0.45176438 0.87482322]
 [0.28488923 0.43902259 0.33451709 0.40364379 0.03889278 0.07706236
  0.30185885 0.63161738 0.04908742 0.55141321]
 [0.70870663 0.35153166 0.71401349 0.07712868 0.52252731 0.30976441
  0.81631907 0.08023918 0.3770705  0.62152911]
 [0.33997067 0.04300722 0.64250614 0.63253415 0.3947701  0.76823013
  0.1871818  0.20131303 0.76883217 0.96717568]
 [0.03009976 0.91416963 0.37209239 0.71923589 0.97688124 0.9315795
  0.30250555 0.06147453 0.87701548 0.36603773]
 [0.44265156 0.04685928 0.1872969  0.29355443 0.54022622 0.24303254
  0.77320636 0.88568555 0.22567274 0.30179952]
 [0.68959631 0.02137651 0.90645908 0.07566445 0.0606759  0.69192484
  0.77874953 0.46122365 0.78500273 0.53266376]
 [0.7774819  0.06048261 0.70309044 0.25995603 0.3080281  0.57371567
  0.86731693 0.07857477 0.22745334 0.43154789]
 [0.99376862 0.67408901 0.01968993 0.95490472 0.41232

### Q14. Create a random vector of size 30 and find the mean value

In [11]:
random_vector = np.random.random(30)
mean_value = random_vector.mean()
print(mean_value)

0.5773608058716266


### Q15. Create a 2d array with 1 on the border and 0 inside

In [13]:
border_array = np.ones((6, 6))
border_array[1:-1, 1:-1] = 0
print(border_array)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


### Q16. How to add a border (filled with 0's) around an existing array?

In [14]:
existing_array = np.ones((5, 5))
new_array = np.pad(existing_array, pad_width=1, mode='constant', constant_values=0)
print(new_array)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


### Q17. What is the result of the following expression?

In [15]:
print(0 * np.nan)  
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan])) 
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


### Q18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [16]:
diagonal_matrix = np.diag(1 + np.arange(4), k=-1)
print(diagonal_matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


### Q19. Create an 8x8 matrix and fill it with a checkerboard pattern

In [17]:
checkerboard_matrix = np.zeros((8, 8), dtype=int)
checkerboard_matrix[1::2, ::2] = 1
checkerboard_matrix[::2, 1::2] = 1
print(checkerboard_matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### Q20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [18]:
shape = (6,7,8)
index_term = 100

# creating an empty array with the shape given
arr = np.empty(shape)

# finding the (x,y,z) of the 100th element
index_value = np.unravel_index(index_term , shape)
index_value

(1, 5, 4)

### Q21. Create a checkerboard 8x8 matrix using the tile function

In [19]:
checkerboard = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### Q22. Normalize a 5x5 random matrix

In [26]:
Array = np.random.random((5, 5))
Array_NORMALIZE = (A - A.min()) / (A.max() - A.min())
print(Array_NORMALIZE)

[[0.02546439 0.26114199 0.17907831]
 [0.78505703 0.15995758 1.        ]
 [0.         0.8321204  0.52972416]
 [0.05526451 0.06370076 0.38813612]
 [0.58311154 0.16789818 0.80714113]]


### Q23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [27]:
color = np.dtype([('R', np.ubyte),
                    ('G', np.ubyte),
                    ('B', np.ubyte),
                    ('A', np.ubyte)])

### Q24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [29]:
array1 = np.random.random((5, 3))
array2 = np.random.random((3, 2))
print(np.dot(array1, array2))

[[1.12986906 0.4850309 ]
 [0.68427406 0.5243283 ]
 [0.65244098 0.39284134]
 [0.74912373 0.64288893]
 [0.51831634 0.3976981 ]]


### Q25. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [32]:
myarray = np.arange(10)
myarray[(myarray > 3) & (myarray < 8)] *= -1
print(myarray)

[ 0  1  2  3 -4 -5 -6 -7  8  9]


### Q26. What is the output of the following script?

In [33]:
# Author: Jake VanderPlas
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


### Q27. Consider an integer vector Z, which of these expressions are legal?

In [34]:
Z = np.arange(5)
print(Z**Z)         # The element-wise power is legal
print(2 << Z >> 2)  # the bitwise shift is also legal
print(Z <- Z)       # the element-wise comparison is legal
print(1j*Z)         # the complex multiplication is legal also
print(Z/1/1)        # the element-wise division is legal
print(Z<Z>Z)        # the chained comparison is illegal

[  1   1   4  27 256]
[0 1 2 4 8]
[False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[0. 1. 2. 3. 4.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### Q28. What are the result of the following expressions?

In [39]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\Engr. CY\AppData\Local\Temp\ipykernel_34252\3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\Engr. CY\AppData\Local\Temp\ipykernel_34252\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\Engr. CY\AppData\Local\Temp\ipykernel_34252\3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


### Q29. How to round away from zero a float array?

In [47]:

arr = np.array([-1.5, 0.2, -0.3, 0.0])

signs = np.sign(arr)
rounded = np.abs(np.round(arr)) * signs

print(rounded)  


[-2.  0. -0.  0.]


### Q30. How to find common values between two arrays?

In [42]:
arr1 = np.array([8, 1, 2, 4, 0])
arr2 = np.array([10, 4, 1, 2, 7])
common = np.intersect1d(A, B)
print(common)

[1 2 4]


### Q31. How to ignore all numpy warnings (not recommended)?

In [46]:
np.seterr(all='ignore')
np.arange(10) / 0

array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf])

### Q32. Is the following expression true?

In [48]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

### Q33. How to get the dates of yesterday, today and tomorrow?

In [50]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today = np.datetime64('today')
tomorrow = np.datetime64('today') + np.timedelta64(1)
print(f"Yesterday Date: {yesterday}")
print(f"Todays Date: {today}")
print(f"Tomorrow Date: {tomorrow}")

Yesterday Date: 2024-02-23
Todays Date: 2024-02-24
Tomorrow Date: 2024-02-25


### Q34. How to get all the dates corresponding to the month of July 2016?

In [51]:
dates_july_2016 = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(dates_july_2016)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


### Q35. How to compute ((A+B)*(-A/2)) in place (without copy)?

In [54]:
A = np.ones(4)
B = np.ones(4) * 2
print(A)
print(B)
print(np.multiply(A + B, -A / 2, out=(A + B)))


[1. 1. 1. 1.]
[2. 2. 2. 2.]
[-1.5 -1.5 -1.5 -1.5]


### Q36. Extract the integer part of a random array of positive numbers using 4 different methods

In [55]:
A = np.random.uniform(0, 15, 10)
print(A.astype(int))
print(np.floor(A))
print(np.ceil(A) - 1)
print(np.trunc(A))

[14  8 11  7  1 13 11  4 11  1]
[14.  8. 11.  7.  1. 13. 11.  4. 11.  1.]
[14.  8. 11.  7.  1. 13. 11.  4. 11.  1.]
[14.  8. 11.  7.  1. 13. 11.  4. 11.  1.]


### Q37. Create a 5x5 matrix with row values ranging from 0 to 4

In [56]:
A = np.tile(np.arange(5), (5, 1))
print(A)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


### Q38. Consider a generator function that generates 10 integers and use it to build an array

In [38]:
def generator():
    for i in range(10):
        yield i

print(np.fromiter(generator(), dtype=int))

[0 1 2 3 4 5 6 7 8 9]


### Q39. Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [59]:
array = np.linspace(0, 1, 12)[1:-1]
print(array)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


### Q40. Create a random vector of size 10 and sort it

In [61]:
array = np.random.random(10)
array.sort()
print(array)

[0.02089969 0.07530075 0.12994407 0.27526441 0.473244   0.52535052
 0.60789067 0.61667215 0.72528025 0.74275905]


### Q41. How to sum a small array faster than np.sum?

In [62]:
array = np.arange(10)
print(np.add.reduce(array))

45


### Q42. Consider two random array A and B, check if they are equal

In [42]:
A = np.random.random(5)
B = np.random.random(5)
print(np.array_equal(A, B))

False


### Q43. Make an array immutable (read-only)

In [64]:
array = np.zeros(15)
array.flags.writeable = False
try:
    A[0] = 7 
except ValueError as e:
    print(f"Error: {e}")

### Q44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

In [65]:
A = np.random.random((10, 2))
x, y = A[:, 0], A[:, 1]
r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)
print(np.column_stack((r, theta)))

[[0.02568471 0.7233336 ]
 [0.98195332 0.07440339]
 [0.62339192 0.82158124]
 [0.68422841 0.4992969 ]
 [0.62044363 0.18122149]
 [0.80807038 0.43667686]
 [1.04785905 0.34781678]
 [0.5195047  1.45013467]
 [0.28525338 0.08418091]
 [0.81901778 0.14719071]]


### Q45. Create random vector of size 10 and replace the maximum value by 0

In [66]:
A = np.random.random(10)
A[A.argmax()] = 0
print(A)

[0.53487375 0.13120488 0.34264698 0.53251566 0.         0.6466924
 0.1299709  0.35022311 0.77999867 0.25449138]


### Q46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area

In [71]:
A = np.zeros((5, 5), [('x', float), ('y', float)])
A['x'], A['y'] = np.meshgrid(np.linspace(0, 1, 5),
np.linspace(0, 1, 5))
print(A)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


### Q47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij = 1/(xi - yj))

In [72]:
X = np.arange(15)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

-9391966.027650956


### Q48. Print the minimum and maximum representable value for each numpy scalar type

In [74]:
for dtype in np.sctypes['int'] + np.sctypes['uint'] + [np.float16, np.float32, np.float64]:
    if np.issubdtype(dtype, np.integer):
        info = np.iinfo(dtype)
        print(f"{dtype}: {info.min} to {info.max}")
    elif np.issubdtype(dtype, np.floating):
        info = np.finfo(dtype)
        print(f"{dtype}: {info.min} to {info.max}")

<class 'numpy.int8'>: -128 to 127
<class 'numpy.int16'>: -32768 to 32767
<class 'numpy.int32'>: -2147483648 to 2147483647
<class 'numpy.int64'>: -9223372036854775808 to 9223372036854775807
<class 'numpy.uint8'>: 0 to 255
<class 'numpy.uint16'>: 0 to 65535
<class 'numpy.uint32'>: 0 to 4294967295
<class 'numpy.uint64'>: 0 to 18446744073709551615
<class 'numpy.float16'>: -65504.0 to 65504.0
<class 'numpy.float32'>: -3.4028234663852886e+38 to 3.4028234663852886e+38
<class 'numpy.float64'>: -1.7976931348623157e+308 to 1.7976931348623157e+308


### Q49. How to print all the values of an array?

In [77]:
np.set_printoptions(threshold=np.inf)
thearray = np.arange(50)
print(thearray)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


### Q50. How to find the closest value (to a given scalar) in a vector?

In [78]:
array = np.arange(15)
scalar = 7.5
closest = array[(np.abs(array - scalar)).argmin()]
print(closest)

7


### Q51. Create a structured array representing a position (x,y) and a color (r,g,b)

In [79]:
array = np.zeros(1, [('position', [('x', int), ('y', int)]),
('color', [('r', int), ('g', int), ('b', int)])])
print(A)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances

In [82]:
vector = np.random.random((100,2))
X,Y = np.atleast_2d(vector[:,0], vector[:,1])
point_Distance = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(point_Distance)


[[0.         0.17420431 0.44714051 0.63524134 0.60329209 0.46248936
  0.50705449 0.6458923  0.55027019 0.49373774 0.60771533 0.43472977
  0.54922307 0.80232585 0.27002201 0.46278498 0.38837676 0.28623105
  0.61679242 0.42427891 0.770123   0.42224852 0.80443254 0.56150299
  0.37371085 0.80734938 0.51928284 0.69726369 0.44992418 0.59881603
  0.4473012  0.44145502 0.52791117 0.30480117 0.76926272 0.37520986
  0.76209323 0.59919867 0.48535967 0.49811275 0.39130219 0.12507137
  0.44139753 0.37139696 0.2669472  0.65736299 0.70168961 0.21572789
  0.46611025 0.63757777 0.51065072 0.24070665 0.25516993 0.18220665
  0.47957402 0.40275758 0.7765522  0.64575858 0.7814075  0.23685033
  0.1730754  0.77602985 0.57338474 0.61649403 0.63134997 0.3537717
  0.7205256  0.52854709 0.34334519 0.4216521  0.54726789 0.30003352
  0.3470417  0.79987823 0.41328116 0.20982005 0.74768336 0.64990026
  0.17818491 0.33244669 0.7597545  0.72198364 0.55120173 0.35984371
  0.46587516 0.51584516 0.41694431 0.30735467 0.3

### Q53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [83]:
float32bit = np.arange(10, dtype=np.float32)
int32bit = float32bit.view(np.int32)
print(int32bit)

[         0 1065353216 1073741824 1077936128 1082130432 1084227584
 1086324736 1088421888 1090519040 1091567616]


### Q54. How to read the following file?

In [85]:
from io import StringIO

file = StringIO('''1, 2, 3, 4, 5
     6,  ,  , 7, 8
     ,  , 9,10,11
''')

fromtexttoarray = np.genfromtxt(file, delimiter=",", dtype=np.int_)
print(fromtexttoarray)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


### Q55. What is the equivalent of enumerate for numpy arrays?

In [86]:
A = np.arange(9).reshape(3, 3)
for index, value in np.ndenumerate(A):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


### Q56. Generate a generic 2D Gaussian-like array

In [87]:
import numpy as np
x, y = np.meshgrid(np.linspace(-1, 1, 5), np.linspace(-1, 1, 5))
d = np.sqrt(x*x + y*y)
sigma, mu = 1.0, 0.0
gaussian_array = np.exp(-( (d-mu)**2 / ( 2.0 * sigma**2 ) ))
print(gaussian_array)

[[0.36787944 0.53526143 0.60653066 0.53526143 0.36787944]
 [0.53526143 0.77880078 0.8824969  0.77880078 0.53526143]
 [0.60653066 0.8824969  1.         0.8824969  0.60653066]
 [0.53526143 0.77880078 0.8824969  0.77880078 0.53526143]
 [0.36787944 0.53526143 0.60653066 0.53526143 0.36787944]]


### Q57. How to randomly place p elements in a 2D array?

In [89]:
p = 4
twoDarray = np.zeros((5, 5))
np.put(twoDarray, np.random.choice(range(5*5), p, replace=False), 1)
print(twoDarray)

[[1. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]


### Q58. Subtract the mean of each row of a matrix

In [90]:
A = np.random.random((3, 3))
B = A - A.mean(axis=1, keepdims=True)
print(B)

[[-0.56231299  0.26703376  0.29527923]
 [ 0.12016904 -0.06767301 -0.05249602]
 [-0.07386975 -0.38298983  0.45685957]]


### Q59. How to sort an array by the nth column?

In [92]:
A = np.random.randint(0, 10, (4, 4))
n = 1
sorted_A = A[A[:, n].argsort()]
print(sorted_A)


[[7 2 5 8]
 [0 3 6 6]
 [6 4 4 1]
 [9 8 0 0]]


### Q60. How to tell if a given 2D array has null columns?

In [102]:
A = np.array([[0, 0, 0], [0, 1, 0], [0, 0, 0]])
null_columns = np.all(A == 0, axis=0)
print(null_columns)

[ True False  True]


### Q61. Find the nearest value from a given value in an array

In [103]:
myvalue = 8
randomvalues = np.random.random(15)
nearest_value = randomvalues[np.abs(randomvalues - myvalue).argmin()]
print(nearest_value)

0.8052908369468956


### Q62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?

In [106]:
array1 = np.arange(3).reshape(1, 3)
array2 = np.arange(3).reshape(3, 1)
sum_the_iterator = np.nditer([array1, array2, None])
for i, j, k in sum_the_iterator:
    k[...] = i + j
print(sum_the_iterator.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


### Q63. Create an array class that has a name attribute

In [107]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name=""):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj

    def __array_finalize__(self, obj):
        if obj is None:
            return
        self.info = getattr(obj, 'name', "")

A = NamedArray(np.arange(5), "range_5")
print (A.name)

range_5


### Q64. Consider a given vector, how to add 1 to each element indexed by a second vector

In [110]:
A = np.ones(10)
vector_indices = np.array([0, 8, 1, 3, 3, 4, 4, 5, 5,6, 6])
np.add.at(A, vector_indices, 1)
print(A)

[2. 2. 1. 3. 3. 3. 3. 1. 2. 1.]


### Q65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?

In [111]:
X = np.array([2, 4, 6, 8, 9, 7])
I = np.array([1, 3, 9, 3, 7, 1])
F = np.bincount(I, weights=X)
print(F)

[ 0.  9.  0. 12.  0.  0.  0.  9.  0.  6.]


### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors

In [66]:
image = np.random.randint(0, 256, (100, 100, 3), dtype=np.ubyte)
unique_colors = len(np.unique(image.reshape(-1, 3), axis=0))
print(unique_colors)

9996


### Q67. Considering a four dimensions array, how to get sum over the last two axis at once?

In [67]:
A = np.random.randint(0,10,(2, 3, 4, 5))
sum_last_two_axes = A.sum(axis=(-2, -1))
print(sum_last_two_axes)

[[ 98  72  63]
 [104 122  85]]


### Q68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of the same size describing subset indices?

In [113]:
vector_D = np.random.random(10)
vector_S = np.random.randint(0, 2, 10)
means_subsets = np.bincount(vector_S, weights=vector_D) / np.bincount(vector_S)
print(means_subsets)

[0.2946623  0.44319034]


### Q69. How to get the diagonal of a dot product?


In [114]:
A = np.random.random((3, 3))
B = np.random.random((3, 3))
diagonal_dot_product = np.diag(np.dot(A, B))
print(diagonal_dot_product)

[0.49044669 0.50468223 1.5750225 ]


### Q70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?


In [115]:
A = np.array([1, 2, 3, 4, 5])
B = np.zeros(len(A)+ (len(A) - 1) * 3, dtype=int)
B[::4] = A
print(B)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


### Q71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)?

In [116]:
A_3d = np.ones((5, 5, 3))
A_2d = 3*np.ones((5, 5))
X = A_3d * A_2d[:, :, None]
print(X)

[[[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]

 [[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]

 [[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]

 [[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]

 [[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]]


#### Q72. How to swap two rows of an array?

In [117]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A[[0, 1]] = A[[1, 0]]
print(A)

[[4 5 6]
 [1 2 3]
 [7 8 9]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles

In [120]:
triplets_array = np.random.randint(0, 10, (10, 3))
uls = np.unique(triplets_array[:, [0, 1, 1, 2, 2, 0]].reshape(-1, 2), axis=0)
print(uls)

[[0 6]
 [0 9]
 [2 2]
 [2 4]
 [2 5]
 [2 6]
 [2 8]
 [3 4]
 [4 2]
 [4 5]
 [4 8]
 [4 9]
 [5 0]
 [5 2]
 [5 3]
 [5 4]
 [5 5]
 [5 6]
 [6 2]
 [6 5]
 [8 2]
 [8 9]
 [9 0]
 [9 2]
 [9 4]
 [9 9]]


In [122]:
triplets_array = np.random.randint(0, 10, (10, 3))
A = np.roll(triplets_array.repeat(2, axis=1), -1, axis=1)
A = A.reshape(len(A) * 3, 2)
A = np.sort(A, axis=1)
B = A.view(dtype=[('p0', A.dtype), ('p1', A.dtype)])
B = np.unique(B)

print(B)

[(0, 0) (0, 3) (0, 4) (0, 7) (0, 8) (1, 1) (1, 4) (1, 7) (2, 3) (2, 7)
 (3, 4) (3, 7) (3, 9) (4, 7) (4, 8) (4, 9) (6, 8) (6, 9) (8, 8) (8, 9)]


### Q74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?

In [123]:
C = np.bincount([0,8,1,6,2,5,4,6,5,0,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[0 0 1 2 4 5 5 6 6 6 8]


### Q75. How to compute averages using a sliding window over an array? 

In [125]:
from numpy.lib.stride_tricks import sliding_window_view

my_array = np.arange(50)
print(sliding_window_view(my_array, window_shape=3).mean(axis=-1))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36.
 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48.]


### Q76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])

In [77]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


### Q77. How to negate a boolean, or to change the sign of a float inplace?

In [126]:
A = np.random.randint(0,2,100)
np.logical_not(A, out=A)

array([0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0])

### Q78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? 

In [127]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[6.69381688 7.07005589 8.49051689 9.59359533 4.43808005 9.43183342
 8.37602219 5.74266276 2.60568108 2.40701219]


### Q79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])?
`

In [80]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))\
    
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[11.22552444  5.39508473  3.32517198  9.1345634   0.35948655  6.60496769
  15.82876342  5.73364988  4.48805176  6.13050084]
 [ 8.73396753  2.07897655  0.33435358  6.00554652  3.31108891  9.73402149
  12.30594079  7.1057225   1.05276959  7.70800655]
 [ 0.51097398  5.15334806  3.1250524   7.787203    6.56261488  7.95255255
   6.23107034  0.13705502  5.59225277  0.89373232]
 [ 7.76763053  0.11257433  3.2005559   2.99586705  6.1252702  12.7437085
  10.00125767  9.29207811  1.09792881 10.01880151]
 [ 1.00444145  5.5539957   6.04123872  3.30723026  9.27197467 12.43247874
   5.03887282  4.90722611  6.41111565  5.97214693]
 [11.15542923  1.53506893  4.78930425  0.89872857  7.44352367 16.63822316
  10.53375773 14.93178247  0.13985595 15.58227238]
 [10.1333521   6.86593162  7.94111779 15.48440157  4.72852701  0.25517485
  18.3185993   0.77630691  6.5002423   0.48184105]
 [ 3.58598073 10.26491539  9.80870151  1.23520264 13.17556375 14.50458832
   0.47778101  4.03403064 11.05771403  5.3854051 ]
 

### Q80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary)

In [129]:
def extract_subpart(array, shape, center):
    subpart = np.full(shape, fill_value=np.nan)
    indices = np.array(center) - np.array(shape) // 2
    subpart_shape = np.minimum(shape, np.array(array.shape) - indices)
    subpart[
        tuple(slice(max(0, -i), dim) for i, dim in zip(indices, subpart_shape))
    ] = array[
        tuple(slice(max(0, i), min(dim, i + s)) for i, s, dim in zip(indices, subpart_shape, array.shape))
    ]
    return subpart

A = np.random.random((15, 15))
subpart = extract_subpart(A, (3, 3), (5, 5))
print(subpart)


[[0.9337067  0.92752189 0.21348675]
 [0.05188155 0.94591641 0.18703007]
 [0.38852418 0.26028522 0.63590402]]


### Q81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R

In [130]:
Z = np.arange(1, 15)
R = np.lib.stride_tricks.sliding_window_view(Z, (4,))
print(R)


[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


### 82. Compute a matrix rank

In [132]:
matrix_rank = np.linalg.matrix_rank(np.random.random((4, 4)))
print(matrix_rank)

4


### Q83. How to find the most frequent value in an array?

In [134]:
A = np.random.randint(0, 10, 40)
frequent_value = np.bincount(A).argmax()
print(A)
print( frequent_value)

[8 6 0 8 8 1 5 6 9 2 3 2 7 8 6 1 1 7 2 6 4 4 2 1 3 2 2 2 9 8 2 9 2 2 2 4 9
 5 3 8]
2


### Q84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix

In [136]:
A = np.random.randint(0,5,(10,10))
print(sliding_window_view(A, window_shape=(3, 3)))

[[[[1 3 0]
   [3 0 2]
   [1 1 4]]

  [[3 0 4]
   [0 2 4]
   [1 4 1]]

  [[0 4 1]
   [2 4 2]
   [4 1 1]]

  [[4 1 2]
   [4 2 2]
   [1 1 1]]

  [[1 2 0]
   [2 2 1]
   [1 1 1]]

  [[2 0 2]
   [2 1 1]
   [1 1 1]]

  [[0 2 0]
   [1 1 4]
   [1 1 3]]

  [[2 0 2]
   [1 4 3]
   [1 3 3]]]


 [[[3 0 2]
   [1 1 4]
   [0 3 4]]

  [[0 2 4]
   [1 4 1]
   [3 4 2]]

  [[2 4 2]
   [4 1 1]
   [4 2 3]]

  [[4 2 2]
   [1 1 1]
   [2 3 4]]

  [[2 2 1]
   [1 1 1]
   [3 4 3]]

  [[2 1 1]
   [1 1 1]
   [4 3 4]]

  [[1 1 4]
   [1 1 3]
   [3 4 0]]

  [[1 4 3]
   [1 3 3]
   [4 0 0]]]


 [[[1 1 4]
   [0 3 4]
   [1 4 4]]

  [[1 4 1]
   [3 4 2]
   [4 4 1]]

  [[4 1 1]
   [4 2 3]
   [4 1 4]]

  [[1 1 1]
   [2 3 4]
   [1 4 1]]

  [[1 1 1]
   [3 4 3]
   [4 1 4]]

  [[1 1 1]
   [4 3 4]
   [1 4 2]]

  [[1 1 3]
   [3 4 0]
   [4 2 1]]

  [[1 3 3]
   [4 0 0]
   [2 1 0]]]


 [[[0 3 4]
   [1 4 4]
   [3 2 4]]

  [[3 4 2]
   [4 4 1]
   [2 4 3]]

  [[4 2 3]
   [4 1 4]
   [4 3 0]]

  [[2 3 4]
   [1 4 1]
   [3 0 1]]

  [[3 4 3]
   

### Q85. Create a 2D array subclass such that Z[i,j] == Z[j,i]

In [137]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(A):
    return np.asarray(A + A.T - np.diag(A.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 6 13 10 14  9]
 [13  2  9 12  2]
 [10  9  8 42 14]
 [14 12 42  5  9]
 [ 9  2 14  9  9]]


### Q86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1))

In [138]:
p = 2
n = 4
matrices = np.random.random((p, n, n))
vectors = np.random.random((p, n, 1))
sum_matrix_products = np.sum(matrices @ vectors, axis=0)
print(sum_matrix_products)

[[1.11014836]
 [1.122976  ]
 [1.82560342]
 [0.97764473]]


### Q87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)?

In [139]:
A = np.ones((16, 16))
block_sum = np.sum(np.lib.stride_tricks.sliding_window_view(A, (4, 4)), axis=(-2, -1))
print(block_sum[::4, ::4, ...])


[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


### 88. How to implement the Game of Life using numpy arrays?

In [140]:
def game_of_life(board, steps):
    for _ in range(steps):
        neighbors = sum(np.roll(np.roll(board, i, axis=0), j, axis=1)
                        for i in (-1, 0, 1) for j in (-1, 0, 1) if (i != 0 or j != 0))
        board = (neighbors == 3) | (board & (neighbors == 2))
    return board

# Example usage:
initial_board = np.random.choice([0, 1], (50, 50))
final_board = game_of_life(initial_board, steps=10)
print(final_board)

[[0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 1 1 0 0 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0 0
  0 0 0 0 0 0 1 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
  1 1 0 0 0 0 1 1 1 0 0 0 1 0]
 [1 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 1 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0 0 0 0 0 1 0 1 0 1 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 1 1 0 0 0 1 1 0 0]
 [0 1 1 0 1 0 0 0 0 0 0 1 0 0 1 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 1 0 0 0 1 1 0 0 0 0 1 1 0]
 [0 0 1 0 1 0 0 0 0 0 0 0 1 0 0 1 1 1 0 0 0 1 0 1 0 0 0 0 0 0 1 1 0 0 0 0
  0 0 0 0 0 0 0 0 0 1 0 1 0 0]
 [0 0 1 0 0 1 0 0 0 0 0 0 0 1 0 0 1 1 0 0 1 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0
  0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 1 0 1 0 0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1
  1 0 0 1 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 1 1 0 0 0 0 1 1 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0
  0 0 0 1 0 0 0 0 0 1 1 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 1 0 0 0 0 0 0 0 0 0 0 1

C:\Users\Engr. CY\AppData\Local\Temp\ipykernel_34252\3694431743.py:3: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  neighbors = sum(np.roll(np.roll(board, i, axis=0), j, axis=1)


### Q89. How to get the n largest values of an array

In [90]:
A = np.arange(100)
n_largest_indices = np.argsort(A)[-n:]
n_largest_values = A[n_largest_indices]
print(n_largest_values)

[95 96 97 98 99]


### Q90. Given an arbitrary number of vectors, build the cartesian product


In [141]:
import itertools

def cartesian(arrays):
    return np.array(list(itertools.product(*arrays)))

result = cartesian(([1, 2, 3], [4, 5], [6, 7]))
print(result)

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


### Q91. How to create a record array from a regular array?

In [142]:

data = np.array([('apple', 5, 1.2), ('banana', 3, 1.5), ('orange', 7, 2.0)],
              dtype=[('fruit', 'U10'), ('count', int), ('price', float)])

Record_array = np.array(data, dtype=[('fruit', 'U10'), ('count', int), ('price', float)])
print(Record_array)


[('apple', 5, 1.2) ('banana', 3, 1.5) ('orange', 7, 2. )]


### Q92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods

In [2]:

Z = np.random.random(1000000)

# Method 1: Using the ** operator
result_1 = Z ** 3

# Method 2: Using np.power function
result_2 = np.power(Z, 3)

# Method 3: Using np.einsum for element-wise cube
result_3 = np.einsum('i,i,i->i', Z, Z, Z)

print("Method 1 result:", result_1)
print("Method 2 result:", result_2)
print("Method 3 result:", result_3)



Method 1 result: [1.38813167e-03 2.79199986e-01 1.78027167e-04 ... 4.40520199e-01
 3.17534183e-01 3.10178818e-02]
Method 2 result: [1.38813167e-03 2.79199986e-01 1.78027167e-04 ... 4.40520199e-01
 3.17534183e-01 3.10178818e-02]
Method 3 result: [1.38813167e-03 2.79199986e-01 1.78027167e-04 ... 4.40520199e-01
 3.17534183e-01 3.10178818e-02]


### Q93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?

In [3]:
A = np.random.randint(0,10,(8,3))
B = np.random.randint(0,10,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[1 3]


### Q94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3])

In [4]:
A = np.random.randint(0, 10, (10, 3))

condition = A[np.any(A[:, 1:] != A[:, :-1], axis=1)]

print(condition)

[[8 1 2]
 [0 8 3]
 [1 6 4]
 [7 2 9]
 [2 1 0]
 [6 8 9]
 [1 9 1]
 [8 6 0]
 [1 3 7]
 [6 5 5]]


### Q95. Convert a vector of ints into a matrix binary representation

In [7]:
vector = np.array([0, 2,3,4,6,8,7,9,10,30,24,70])
convert = ((vector.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(convert[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 1 1 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 1 1]
 [0 0 0 0 1 0 0 1]
 [0 0 0 0 1 0 1 0]
 [0 0 0 1 1 1 1 0]
 [0 0 0 1 1 0 0 0]
 [0 1 0 0 0 1 1 0]]


### Q96. Given a two dimensional array, how to extract unique rows?

In [9]:
myarray = np.array([[1, 2, 3],
              [4, 5, 6],
              [1, 2, 3],
              [7, 8, 9],
              [4, 5, 6]])

unique_rows = np.unique(myarray, axis=0)

print(unique_rows)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Q97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function

In [10]:
A = np.random.uniform(1,5,10)
B = np.random.uniform(1,2,10)

# Inner Product
I = np.einsum('i,i->', A, B)
print( f"Result of Inner Product: \n{I}")

# Outer Product
O = np.einsum('i,j->ij', A, B)
print( f"Result of Outer Product: \n{O}")

# Sum
S= np.einsum('i->', A) 
print( f"Result of Sum: \n{S}")

# Element-wise Multiplication
M = np.einsum('i,i->i', A, B)
print( f"Result of Multiplication: \n{ M}")

Result of Inner Product: 
43.11189064378193
Result of Outer Product: 
[[3.42694804 4.93062188 4.50271737 2.92531103 4.62335969 2.83421485
  4.18125867 4.80867792 3.49744323 4.03242976]
 [1.86604467 2.68482644 2.45182351 1.59289286 2.51751577 1.54328909
  2.27678254 2.61842541 1.90443078 2.1957421 ]
 [3.62310487 5.21284827 4.76045071 3.09275441 4.88799854 2.99644393
  4.42059187 5.0839243  3.69763517 4.26324407]
 [1.94197954 2.79407995 2.55159545 1.65771238 2.61996092 1.60609008
  2.36943154 2.72497687 1.98192769 2.28509332]
 [4.27298385 6.1478807  5.61433626 3.64750404 5.76476244 3.53391828
  5.21351669 5.99583154 4.36088272 5.02794529]
 [4.05723304 5.8374629  5.3308581  3.46333485 5.47368898 3.35548425
  4.95027664 5.69309098 4.14069373 4.77407509]
 [3.53646245 5.08818896 4.64660997 3.01879472 4.77110764 2.92478739
  4.31487847 4.96234805 3.60921045 4.16129346]
 [3.88732324 5.59300019 5.10761111 3.31829646 5.24446049 3.21496245
  4.74296774 5.45467431 3.96728874 4.5741452 ]
 [4.017244

### Q98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples

In [12]:
def sample_path(X, Y, num_samples):
    # Calculate the total length of the path
    distances = np.sqrt(np.diff(X)**2 + np.diff(Y)**2)
    total_length = np.sum(distances)
    
    # Calculate the step size for equidistant sampling
    step_size = total_length / (num_samples - 1)
    
    sampled_points = []
    sampled_points.append((X[0], Y[0]))  # Add the starting point
    
    current_length = 0
    for i in range(len(X) - 1):
        # Calculate the distance between consecutive points
        distance = np.sqrt((X[i + 1] - X[i])**2 + (Y[i + 1] - Y[i])**2)
        
        # If the next point contributes to surpassing the current length by the step size
        while current_length + distance >= step_size:
            # Calculate the position of the interpolated point
            fraction = (step_size - current_length) / distance
            interpolated_x = X[i] + (X[i + 1] - X[i]) * fraction
            interpolated_y = Y[i] + (Y[i + 1] - Y[i]) * fraction
            sampled_points.append((interpolated_x, interpolated_y))
            
            # Update the current length and step size
            current_length -= step_size
            step_size = total_length / (num_samples - len(sampled_points) - 1)
        
        current_length += distance
    
    sampled_points.append((X[-1], Y[-1]))  # Add the ending point
    
    return np.array(sampled_points)

# Example usage:
X = np.array([0, 1, 3, 5, 6])
Y = np.array([0, 2, 4, 3, 1])
num_samples = 10

sampled_points = sample_path(X, Y, num_samples)
print("Sampled points:")
print(sampled_points)

Sampled points:
[[0.         0.        ]
 [0.47387901 0.94775801]
 [1.13147488 2.13147488]
 [2.25537763 3.25537763]
 [3.76408335 3.61795832]
 [5.44826944 2.10346112]
 [6.         1.        ]]


### Q99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n.

In [100]:
def select_multinomial_rows(X, n):
    # Check if each element in the array is an integer
    is_integer = np.all(X.astype(int) == X, axis=1)

    # Check if the sum of each row is equal to 'n'
    sum_equals_n = np.sum(X, axis=1) == n

    # Combine the conditions to select rows
    selected_rows = X[is_integer & sum_equals_n]

    return selected_rows

n = 10
X = np.array([[2, 4, 7], [1, 5, 6], [4, 1, 1], [5, 6, 6], [5, 2, 3]])

result = select_multinomial_rows(X, n)
print("Selected Rows:")
print(result)

[[2. 0. 1. 1.]]


### Q100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means).

In [13]:

X = np.random.randn(100)  # Example 1D array
N = 1000  # Number of bootstrap samples

bootstrapped_means = [np.mean(np.random.choice(X, len(X), replace=True)) for _ in range(N)]
confidence_interval = np.percentile(bootstrapped_means, [2.5, 97.5])
print("95% Confidence Interval for the Mean:", confidence_interval)

95% Confidence Interval for the Mean: [-0.12850723  0.2219844 ]
